import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import "@/sass/main.scss";
import StoreProvider from "./StoreProvider";
import ToastNotificationComp from "@/components/toast-notification-comp/ToastNotificationComp";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next js Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer />
          <ToastNotificationComp />
        </body>
      </StoreProvider>
    </html>
  );
}
